### ISSUE TITLE
TypeError: 'Boost.Python.class' object is not iterable

### ISSUE THREAD

**Issue by YoungTMC** [hijkzzz/new_pymarl#42]
```
Traceback (most recent call last):
  File "src/main.py", line 14, in <module>
    from run import REGISTRY as run_REGISTRY
  File "/workspace/pymarl2/src/run/__init__.py", line 1, in <module>
    from .run import run as default_run
  File "/workspace/pymarl2/src/run/run.py", line 12, in <module>
    from learners import REGISTRY as le_REGISTRY
  File "/workspace/pymarl2/src/learners/__init__.py", line 4, in <module>
    from .ppo_learner import PPOLearner
  File "/workspace/pymarl2/src/learners/ppo_learner.py", line 3, in <module>
    from controllers.n_controller import NMAC
  File "/workspace/pymarl2/src/controllers/__init__.py", line 3, in <module>
    from .basic_controller import BasicMAC
  File "/workspace/pymarl2/src/controllers/basic_controller.py", line 2, in <module>
    from components.action_selectors import REGISTRY as action_REGISTRY
  File "/workspace/pymarl2/src/components/action_selectors.py", line 1, in <module>
    from matplotlib.pyplot import xcorr
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/matplotlib/__init__.py", line 129, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "/root/anaconda3/envs/pymarl/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 2048, in <module>
    class _OrderedSet(collections.abc.MutableSet):
  File "/root/anaconda3/envs/pymarl/lib/python3.8/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: 'Boost.Python.class' object is not iterable
```

Hello，运行README中的样例时报了这个错，请问该怎么解决呢？

**Comment by hijkzzz** [comment]
应该是环境依赖问题，很久没更新了可以debug一下。或者参考 pymarl3。
